version: '3.8'
services:
  dorahack-chat-backend:
    container_name: dorahack-chat-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
